### ISSUE TITLE
Windows 10 installation

### ISSUE THREAD

**Issue by nikshriv** [finnfiddle/words-to-numbers#19] opened 2018-03-05 22:08 UTC
Initially, I could not install this using npm on a windows 10 machine as it apparently requires 'bash'. Installing the windows linux subsystem and free Ubuntu distribution allowed the installation to succeed. 

Any plans for a version that runs on windows without having to install the linux subsystem?

**Comment by finnfiddle** [comment] 2018-04-17 18:43
@nikshriv could this be a duplicate of [this issue](https://github.com/finnfiddle/words-to-numbers/issues/16)?
if so then the problem is with the `ohm-js` package. If you like you can open an issue there

**Comment by finnfiddle** [comment] 2018-04-28 06:43
@nikshriv I just did a major refactor and replaced ohm-js with a custom parser should it should install fine on windows now without any workarounds - as of v1.4.1

**Closed by finnfiddle** 2018-04-28 06:43 UTC
